export const mockOpportunities = [
  {
    id: 1,
    title: "Google Summer of Code 2026",
    description: "Contribute to open source projects during summer and get paid by Google.",
    organizer: "Google",
    deadline: new Date("2026-04-15"),
    opportunityType: "Internship",
    stage: "Undergraduate",
    regions: ["Global"],
    mode: "Online",
    fields: ["Tech", "Engineering"],
    funding: "Paid",
    requirements: "Currently enrolled in university, 18+ years old",
    benefits: "Stipend, mentorship, certificate",
    programStartDate: new Date("2026-06-01"),
    programEndDate: new Date("2026-08-31"),
    fundingAmount: "$3,000 - $6,500",
    applicationLink: "https://summerofcode.withgoogle.com",
    isFeatured: true,
  },
  {
    id: 2,
    title: "Schwarzman Scholars Program",
    description: "Full scholarship for graduate studies at Tsinghua University in Beijing.",
    organizer: "Tsinghua University",
    deadline: new Date("2026-03-31"),
    opportunityType: "Scholarship",
    stage: "Graduate",
    regions: ["Global", "Africa", "India", "Brazil", "LATAM", "Southeast Asia", "East Asia"],
    mode: "In-person",
    fields: ["Business", "Policy", "Engineering"],
    funding: "Fully funded",
    requirements: "Bachelor's degree, strong academic record, leadership potential",
    benefits: "Full tuition, living expenses, mentorship, internship",
    programStartDate: new Date("2026-09-01"),
    programEndDate: new Date("2028-08-31"),
    fundingAmount: "Full coverage",
    applicationLink: "https://schwarzmanscholars.org",
    isFeatured: true,
  },
  {
    id: 3,
    title: "Y Combinator Startup School",
    description: "Free online startup education from Y Combinator founders and investors.",
    organizer: "Y Combinator",
    deadline: new Date("2026-05-30"),
    opportunityType: "Accelerator",
    stage: "Startup idea",
    regions: ["Global"],
    mode: "Online",
    fields: ["Tech", "Business"],
    funding: "Stipend",
    requirements: "Startup idea or MVP, founders from underserved markets preferred",
    benefits: "Free education, networking, potential investment opportunity",
    programStartDate: new Date("2026-06-15"),
    programEndDate: new Date("2026-08-15"),
    fundingAmount: "Up to $500K investment",
    applicationLink: "https://www.startupschool.org",
    isFeatured: true,
  },
  {
    id: 4,
    title: "Ashoka Fellowship",
    description: "Support for social entrepreneurs creating systemic change in their communities.",
    organizer: "Ashoka",
    deadline: new Date("2026-04-30"),
    opportunityType: "Fellowship",
    stage: "MVP",
    regions: ["Global", "Africa", "India", "Brazil", "LATAM"],
    mode: "Hybrid",
    fields: ["Social Impact", "Health", "Climate"],
    funding: "Stipend",
    requirements: "Innovative solution to social problem, 3+ years experience",
    benefits: "Stipend, mentorship, global network, resources",
    programStartDate: new Date("2026-07-01"),
    programEndDate: new Date("2027-06-30"),
    fundingAmount: "$30,000 - $60,000",
    applicationLink: "https://www.ashoka.org",
    isFeatured: false,
  },
  {
    id: 5,
    title: "Fulbright Scholarship Program",
    description: "Educational exchange program for students and professionals worldwide.",
    organizer: "U.S. Department of State",
    deadline: new Date("2026-03-15"),
    opportunityType: "Scholarship",
    stage: "Undergraduate",
    regions: ["Global", "Brazil", "India", "Africa"],
    mode: "In-person",
    fields: ["Business", "Engineering", "Policy", "Design"],
    funding: "Fully funded",
    requirements: "Bachelor's degree, English proficiency, U.S. visa eligible",
    benefits: "Tuition, airfare, health insurance, living allowance",
    programStartDate: new Date("2026-08-01"),
    programEndDate: new Date("2027-05-31"),
    fundingAmount: "Full coverage",
    applicationLink: "https://www.fulbright.org.br",
    isFeatured: true,
  },
  {
    id: 6,
    title: "TechCrunch Disrupt Startup Competition",
    description: "Pitch your startup on the world's biggest stage and compete for $100K.",
    organizer: "TechCrunch",
    deadline: new Date("2026-05-01"),
    opportunityType: "Competition",
    stage: "MVP",
    regions: ["Global"],
    mode: "In-person",
    fields: ["Tech", "Business"],
    funding: "Equity-based",
    requirements: "Registered company, working MVP, founded within 7 years",
    benefits: "$100K prize, media coverage, investor connections",
    programStartDate: new Date("2026-09-15"),
    programEndDate: new Date("2026-09-18"),
    fundingAmount: "$100,000 prize",
    applicationLink: "https://techcrunch.com/disrupt",
    isFeatured: false,
  },
  {
    id: 7,
    title: "Rhodes Scholarship",
    description: "Prestigious scholarship for exceptional students to study at Oxford University.",
    organizer: "University of Oxford",
    deadline: new Date("2026-02-28"),
    opportunityType: "Scholarship",
    stage: "Undergraduate",
    regions: ["Global", "USA/Canada", "Africa"],
    mode: "In-person",
    fields: ["Business", "Engineering", "Policy"],
    funding: "Fully funded",
    requirements: "Exceptional academic record, leadership, age 18-24",
    benefits: "Full tuition, living expenses, mentorship, global network",
    programStartDate: new Date("2026-10-01"),
    programEndDate: new Date("2028-09-30"),
    fundingAmount: "Full coverage",
    applicationLink: "https://www.rhodeshouse.ox.ac.uk",
    isFeatured: true,
  },
  {
    id: 8,
    title: "Climate Tech Innovation Challenge",
    description: "Accelerator program for startups solving climate change challenges.",
    organizer: "Climate Tech Hub",
    deadline: new Date("2026-06-15"),
    opportunityType: "Accelerator",
    stage: "Startup idea",
    regions: ["Global", "Africa", "Brazil", "LATAM", "Southeast Asia"],
    mode: "Hybrid",
    fields: ["Climate", "Tech", "Engineering"],
    funding: "Equity-based",
    requirements: "Climate-focused startup, innovative solution",
    benefits: "Seed funding, mentorship, investor network, resources",
    programStartDate: new Date("2026-08-01"),
    programEndDate: new Date("2026-11-30"),
    fundingAmount: "$50,000 - $200,000",
    applicationLink: "https://climatetechhub.org",
    isFeatured: false,
  },
  {
    id: 9,
    title: "MIT Global Engineering and Research Lab",
    description: "Research opportunity at MIT's labs for international graduate students.",
    organizer: "MIT",
    deadline: new Date("2026-04-01"),
    opportunityType: "Internship",
    stage: "Graduate",
    regions: ["Global"],
    mode: "In-person",
    fields: ["Engineering", "Tech"],
    funding: "Paid",
    requirements: "Master's or PhD candidate, strong research background",
    benefits: "Competitive stipend, housing, research opportunities",
    programStartDate: new Date("2026-06-01"),
    programEndDate: new Date("2026-08-31"),
    fundingAmount: "$3,000 - $5,000/month",
    applicationLink: "https://web.mit.edu",
    isFeatured: false,
  },
  {
    id: 10,
    title: "African Leadership Academy Fellowship",
    description: "Leadership development program for young African leaders.",
    organizer: "African Leadership Academy",
    deadline: new Date("2026-03-20"),
    opportunityType: "Fellowship",
    stage: "Undergraduate",
    regions: ["Africa"],
    mode: "In-person",
    fields: ["Business", "Policy", "Social Impact"],
    funding: "Fully funded",
    requirements: "African resident, 18-25 years old, leadership potential",
    benefits: "Full tuition, accommodation, mentorship, network",
    programStartDate: new Date("2026-07-01"),
    programEndDate: new Date("2026-12-31"),
    fundingAmount: "Full coverage",
    applicationLink: "https://www.africanleadershipacademy.org",
    isFeatured: true,
  },
  {
    id: 11,
    title: "Startup India Seed Fund Scheme",
    description: "Government funding for innovative startups in India.",
    organizer: "Government of India",
    deadline: new Date("2026-05-31"),
    opportunityType: "Grant",
    stage: "Startup idea",
    regions: ["India"],
    mode: "Online",
    fields: ["Tech", "Business", "Climate", "Health"],
    funding: "Grant",
    requirements: "Registered startup in India, innovative business model",
    benefits: "Up to ₹50 lakhs funding, mentorship, incubation support",
    programStartDate: new Date("2026-06-01"),
    programEndDate: new Date("2027-05-31"),
    fundingAmount: "Up to ₹50,00,000",
    applicationLink: "https://www.startupindia.gov.in",
    isFeatured: false,
  },
  {
    id: 12,
    title: "International Conference on AI & Ethics",
    description: "Annual conference bringing together AI researchers and ethicists.",
    organizer: "AI Ethics Foundation",
    deadline: new Date("2026-04-30"),
    opportunityType: "Conference",
    stage: "Graduate",
    regions: ["Global"],
    mode: "In-person",
    fields: ["Tech", "Policy"],
    funding: "Partial",
    requirements: "Research paper or presentation proposal",
    benefits: "Conference attendance, networking, publication opportunity",
    programStartDate: new Date("2026-09-01"),
    programEndDate: new Date("2026-09-03"),
    fundingAmount: "50% travel subsidy",
    applicationLink: "https://aieethics.org/conference",
    isFeatured: false,
  },
  {
    id: 13,
    title: "Erasmus+ Student Exchange Program",
    description: "Study abroad opportunity in European universities.",
    organizer: "European Commission",
    deadline: new Date("2026-02-15"),
    opportunityType: "Exchange Program",
    stage: "Undergraduate",
    regions: ["Global", "Europe", "Brazil", "India"],
    mode: "In-person",
    fields: ["Business", "Engineering", "Design"],
    funding: "Partial",
    requirements: "Enrolled in partner university, EU citizenship or equivalent",
    benefits: "Tuition waiver, monthly stipend, accommodation support",
    programStartDate: new Date("2026-09-01"),
    programEndDate: new Date("2027-06-30"),
    fundingAmount: "€200-300/month",
    applicationLink: "https://erasmusplus.ec.europa.eu",
    isFeatured: false,
  },
  {
    id: 14,
    title: "Techstars Accelerator Program",
    description: "Intensive 3-month accelerator for early-stage startups worldwide.",
    organizer: "Techstars",
    deadline: new Date("2026-06-01"),
    opportunityType: "Accelerator",
    stage: "MVP",
    regions: ["Global"],
    mode: "In-person",
    fields: ["Tech", "Business"],
    funding: "Equity-based",
    requirements: "Early-stage startup, working MVP, cofounder team",
    benefits: "$120K investment, mentorship, investor network, resources",
    programStartDate: new Date("2026-08-01"),
    programEndDate: new Date("2026-10-31"),
    fundingAmount: "$120,000 + equity",
    applicationLink: "https://www.techstars.com",
    isFeatured: true,
  },
  {
    id: 15,
    title: "Mastercard Foundation Scholars Program",
    description: "Scholarship for talented students from Africa, Asia, and Latin America.",
    organizer: "Mastercard Foundation",
    deadline: new Date("2026-03-31"),
    opportunityType: "Scholarship",
    stage: "Undergraduate",
    regions: ["Africa", "India", "Brazil", "LATAM", "Southeast Asia"],
    mode: "In-person",
    fields: ["Business", "Engineering", "Policy"],
    funding: "Fully funded",
    requirements: "High school graduate, demonstrated financial need, leadership",
    benefits: "Full tuition, living expenses, mentorship, internship opportunities",
    programStartDate: new Date("2026-09-01"),
    programEndDate: new Date("2030-06-30"),
    fundingAmount: "Full coverage",
    applicationLink: "https://www.mastercardfdn.org",
    isFeatured: true,
  },
];
